name: my-example-config
common:
  pythonCommand: python3
  pythonVersion: 3.9.10
components:
  - name: baseSubscriber
    outputPath: components/baseSubscriber
    program: baseSubscriber.sh
    args:
      - -v
    restartOnError: true
  - name: basePublisher
    outputPath: components/basePublisher
    program: basePublisher.sh
